services:
  # 1) API — Node/Express (Web Service)
  - type: web
    name: zus-sim-api
    env: node                 # node web service
    plan: starter
    region: frankfurt
    autoDeploy: true
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9.12.0 --activate
      pnpm i --frozen-lockfile
      pnpm -F api build
    startCommand: pnpm -F api start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20.12.2
      - key: PNPM_VERSION
        value: 9.12.0
      - fromGroup: zus-sim-shared
      - fromGroup: zus-sim-api
    disk:
      name: api-logs
      mountPath: /var/data
      sizeGB: 1

  # 2) WEB — Static Site (Vite build)
  - type: web                 # static sites are also 'web'
    name: zus-sim-web
    env: static               # declare static via env: static
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9.12.0 --activate
      pnpm i --frozen-lockfile
      pnpm -F web build
    staticPublishPath: apps/web/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - fromGroup: zus-sim-public
    routes:
      # SPA rewrite: all routes → index.html
      - type: rewrite
        source: /*
        destination: /index.html
