services:
  # 1) API — Node/Express (Web Service)
  - type: web
    name: zus-sim-api
    runtime: node                   # was: env: node
    plan: starter
    region: frankfurt
    autoDeployTrigger: commit       # replaces deprecated autoDeploy
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9.12.0 --activate
      pnpm i --frozen-lockfile
      pnpm -F api build
    startCommand: pnpm -F api start
    healthCheckPath: /health
    healthCheckTimeout: 10
    envVars:
      - key: NODE_VERSION
        value: 20.12.2
      - key: PNPM_VERSION
        value: 9.12.0
      - fromGroup: zus-sim-shared
      - fromGroup: zus-sim-api
    routes:
      - type: rewrite
        source: /.well-known/health
        destination: /health
    disk:
      name: api-logs
      mountPath: /var/data
      sizeGB: 1

  # 2) WEB — Static Site (Vite build)
  - type: web                     # <— static site is also a 'web' service
    name: zus-sim-web
    runtime: static               # <— REQUIRED for static sites
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9.12.0 --activate
      pnpm i --frozen-lockfile
      pnpm -F web build
    staticPublishPath: apps/web/dist   # <— required field for static sites
    previews:
      generation: automatic            # replaces deprecated pullRequestPreviewsEnabled
    envVars:
      - fromGroup: zus-sim-public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
