services:
  # 1) API — Node/Express (Web Service)
  - type: web
    name: zus-sim-api
    env: node
    plan: starter
    runtime: node
    region: frankfurt
    autoDeploy: true
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9.12.0 --activate
      pnpm i --frozen-lockfile
      pnpm -F api build
    startCommand: pnpm -F api start
    healthCheckPath: /health
    healthCheckTimeout: 10
    envVars:
      - key: NODE_VERSION
        value: 20.12.2
      - key: PNPM_VERSION
        value: 9.12.0
      - fromGroup: zus-sim-shared
      - fromGroup: zus-sim-api
    routes:
      # Optional alias for health (keeps bots happy)
      - type: rewrite
        source: /.well-known/health
        destination: /health
    disk:
      name: api-logs
      mountPath: /var/data
      sizeGB: 1

  # 2) WEB — Static Site (Vite build)
  - type: static_site            # <-- IMPORTANT: was "static"
    name: zus-sim-web
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9.12.0 --activate
      pnpm i --frozen-lockfile
      pnpm -F web build
    publishPath: apps/web/dist   # <-- IMPORTANT: was "staticPublishPath"
    pullRequestPreviewsEnabled: true
    envVars:
      - fromGroup: zus-sim-public
    routes:
      # SPA rewrite: all app routes → /index.html
      - type: rewrite
        source: /*
        destination: /index.html
